Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -27,6 +27,12 @@ jobs:
             export NVM_DIR="\$HOME/.nvm"
             [ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"
 
+            # Check if the deployment path exists
+            if [ ! -d "${DEPLOY_PATH}" ]; then
+              echo "Error: Directory ${DEPLOY_PATH} does not exist."
+              exit 1
+            fi
+
             cd ${DEPLOY_PATH}
 
             git checkout main
